### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rushkii** [lico-n/ZygiskFrida#11]
I used `com.mobile.legends,10000` then I used `frida -R gadget` in my Termux, but it says `Failed to spawn: unable to connect to remote frida-server`. But when I don't use delay, it looks everything fine when I used frida command, but suddenly the connection is terminated or either the app crashed. How to solve this?

This is when I don't use delay:
![image](https://github.com/lico-n/ZygiskFrida/assets/47179236/d1bdfee5-ecfb-4353-8c4f-d8fc584da555)

and this is when I use it:
![image](https://github.com/lico-n/ZygiskFrida/assets/47179236/add27e82-4e5d-4123-912b-8e88a69cb0e3)

**Comment by lico-n** [comment]
For me both with and without delay works fine for this application.

Could you please make sure that you don't have any other frida magisk modules installed? This is not really compatible with other frida modules like f.e. MagiskFrida. 

Please provide logs for `adb logcat -v tag | grep -e "Frida"`  or alternatively `adb logcat -s ZygiskFrida`.

**Comment by lico-n** [comment]
As there are no more information I will close this issue.

This doesn't seem to be an issue with ZygiskFrida but with more app specific anti-tamper checks. Purely connecting to the gadget without scripts works. If you try to interact with the libil2cpp, you will get issues because it has more protections built in that are not within the scope of this project.

**Comment by ekko-zhao** [comment]
when I used frida command
<img width="677" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/26781518/b792abc3-c8df-457a-bb99-3ecc1b810bc4">
my command like this
<img width="688" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/26781518/32c58f28-fc6c-4b0a-8614-4146cd561fc0">
How to solve this,thanks!

**Comment by lico-n** [comment]
> when I used frida command <img alt="image" width="677" src="https://user-images.githubusercontent.com/26781518/274232773-b792abc3-c8df-457a-bb99-3ecc1b810bc4.png"> my command like this <img alt="image" width="688" src="https://user-images.githubusercontent.com/26781518/274232892-32c58f28-fc6c-4b0a-8614-4146cd561fc0.png"> How to solve this,thanks!

The current bundled gadget version is 16.x.x. Make sure that your frida cli has the same major version or replace the gadget with the version you are using

**Comment by ekko-zhao** [comment]
Based on the scenario shown in the image below, even though it seems like the injection was successful, is it still getting intercepted by the app's detection mechanism?
<img width="1265" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/26781518/3284e805-465a-4ec8-891e-048d22e165d2">

**Comment by lico-n** [comment]
> Based on the scenario shown in the image below, even though it seems like the injection was successful, is it still getting intercepted by the app's detection mechanism?
> 
> <img width="1265" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/26781518/3284e805-465a-4ec8-891e-048d22e165d2">
> 
> 

Yes, the app is detecting it.
