### ISSUE TITLE
Not attaching on apps on deny list when enforcing Magisk denylist

### ISSUE THREAD

**Issue by altefwan** [lico-n/ZygiskFrida#14]
I'm currently using Magisk Alpha. As the title says, when Enforce Denylist is on and the app is on the deny list, this won't attach the lib. Pardon my ignorance, I don't know if I should post it as an issue as I am ignorant of the behavior of Enforce Denylist.

**Comment by lico-n** [comment]
Hey,

Just checking the official magisk (I am guessing alpha is the same with additional hiding stuff)

https://github.com/topjohnwu/Magisk/blob/877aeb66cb714b25dc86411673b5030ce0c5f5f5/native/src/zygisk/hook.cpp#L560-L565

Enabling denylist will stop any zygisk modules from running on that particular app.

So you might have to use a different root hiding method that still allows zygisk to run. 

I am currently using Magisk Delta with MagiskHide enabled. There are probably other ways (shamiko etc) that might have varying degree of success. But I have not tested these methods.

Anyways ZygiskFrida requires zygisk to run and Denylist will stop it from running, there is nothing I can do here so I will be closing this issue.
