### ISSUE TITLE
Failed to inject /data/local/tmp/re.zyg.fri/libgadget.so : dlopen failed on arm32 app

### ISSUE THREAD

**Issue by altefwan** [lico-n/ZygiskFrida#16]
This works flawlessly on the arm64 version of the game but I forced install the arm32 version of a game for debugging purposes and now I'm getting this error when trying to inject.

**Comment by altefwan** [comment]
I just realized, I may have to use the arm32 gadget. My bad.

**Comment by lico-n** [comment]
For convenience the module now also unpacks the 32-bit gadget on 64-bit devices.

You can adjust the config to use the 32-bit gadget for your use case now.

See https://github.com/lico-n/ZygiskFrida/releases/tag/v1.5.0
