### ISSUE TITLE
Can't seem to connect over network

### ISSUE THREAD

**Issue by altefwan** [lico-n/ZygiskFrida#17]
First of all, thank you for creating this great tool. I've been having a blast trying things out for the past couple of days.

Now unto the problem, I've been using this over USB however my phone is still discharging while connected. So I've been thinking of using this over the network so that I can use the phone charger to charge the phone. However, I can't seem to connect, it always says:

Failed to attach/spawn: unable to connect to remote frida-server

I've tried using both the package name and 'Gadget' but both failed.

**Comment by altefwan** [comment]
As an additional context, I was able to attach locally using termux, but I can't do so when using my PC.

**Comment by lico-n** [comment]
The gadget frida server is only expose to the local device.

If you want to work remotely, you can alternatively do this instead.

- Connect the device by usb 
- On your PC run `adb tcpip 5555` . This exposes the phone adb server for remote access on port 5555.
- Disconnect the phone from your PC
- On your PC connect to the remote adb server by running `adb connect {device-ip-address}:5555` 

Now you have an active remote adb connection and can treat it as if you had a connected device and use the `-U` parameter with frida.
