### ISSUE TITLE
Frida got terminated

### ISSUE THREAD

**Issue by CursedLand** [lico-n/ZygiskFrida#23]
![image](https://github.com/lico-n/ZygiskFrida/assets/75072673/6cb89448-8d88-45f9-a1be-3ca7d3fd85f6)
![image](https://github.com/lico-n/ZygiskFrida/assets/75072673/c07c1025-34bc-414c-956d-4052308b3920)

Did i do something wrong?

Also the Il2cpp game is protected using `libpairipcore.so` (Google Play Integrity).

I tried setting the start up delay to 10s to 50s but app crashes after the test code executes by couple seconds.

The test code:

```javascript
Java.perform(function () { 
    var context = Java.use('android.app.ActivityThread').currentApplication().getApplicationContext();

    Java.scheduleOnMainThread(function() {
            var toast = Java.use("android.widget.Toast");
            toast.makeText(Java.use("android.app.ActivityThread").currentApplication().getApplicationContext(), Java.use("java.lang.String").$new("This is works!"), 1).show();
    });
});
``` 

Thanks for future respond.

**Comment by lico-n** [comment]
I can't really help with app specific protections especially if I don't know what the app is supposed to be. This module does not bypass everything but only some specfpific kinds of checks.

**Comment by CursedLand** [comment]
> I can't really help with app specific protections especially if I don't know what the app is supposed to be. This module does not bypass everything but only some specfpific kinds of checks.

it's Unity game, it was working until last update they attached the new Google Play integrity thing `(libpairipcore.so)`

Some links that explain more about this:

https://github.com/vfsfitvnm/frida-il2cpp-bridge/discussions/431

https://github.com/rednaga/APKiD/issues/329

https://developer.android.com/google/play/integrity/overview

it's not really custom/special protection, but rather google started offering it for games as solution for generic game integrity protection but its if you want to use normal Mod-Menu hooking by editing the dex, but it resists frida mostly, so if you got frida server opened on the phone the game closes immediately, i hope you got it.

Thanks 😊

**Comment by lico-n** [comment]
and what is the game you're testing this on?

**Comment by CursedLand** [comment]
> and what is the game you're testing this on?

https://www.apkmirror.com/apk/kabam/marvel-contest-of-champions/

**Comment by nitanmarcel** [comment]
It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection

**Comment by CursedLand** [comment]
> It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection

which lib uses a svc call?

**Comment by CursedLand** [comment]
> It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection

Just checked `libpairipcore.so` SVC calls and it's none.

![image](https://github.com/lico-n/ZygiskFrida/assets/75072673/eadc50a0-799c-426d-9d41-6edcd9414385)

**Comment by nitanmarcel** [comment]
> > It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection
> 
> Just checked `libpairipcore.so` SVC calls and it's none.
> 
> ![image](https://private-user-images.githubusercontent.com/75072673/301311905-eadc50a0-799c-426d-9d41-6edcd9414385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDI5ODMsIm5iZiI6MTcwNjc0MjY4MywicGF0aCI6Ii83NTA3MjY3My8zMDEzMTE5MDUtZWFkYzUwYTAtNzk5Yy00MjZkLTlkNDEtNmVkY2Q5NDE0Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTk2N2FjYzFlYzQyZTlhNzhjZjUwZmFjMWFlZGNiZjNmNjU2ZDMwMTM2MTM0YThkNmY4MTVjYjdkZTk0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBmgOiZVVxmMqLvANhGWtcaqkZNCm9g5SZLTjYJKTIA)

`/ad/ svc`

**Comment by CursedLand** [comment]
> > > It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection
> > 
> > 
> > Just checked `libpairipcore.so` SVC calls and it's none.
> > ![image](https://private-user-images.githubusercontent.com/75072673/301311905-eadc50a0-799c-426d-9d41-6edcd9414385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDI5ODMsIm5iZiI6MTcwNjc0MjY4MywicGF0aCI6Ii83NTA3MjY3My8zMDEzMTE5MDUtZWFkYzUwYTAtNzk5Yy00MjZkLTlkNDEtNmVkY2Q5NDE0Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTk2N2FjYzFlYzQyZTlhNzhjZjUwZmFjMWFlZGNiZjNmNjU2ZDMwMTM2MTM0YThkNmY4MTVjYjdkZTk0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBmgOiZVVxmMqLvANhGWtcaqkZNCm9g5SZLTjYJKTIA)
> 
> `/ad/ svc`

![image](https://github.com/lico-n/ZygiskFrida/assets/75072673/f9cfb161-87d9-40d9-a32d-42f886038f68)

**Comment by nitanmarcel** [comment]
> > > > It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection
> > > 
> > > 
> > > Just checked `libpairipcore.so` SVC calls and it's none.
> > > ![image](https://private-user-images.githubusercontent.com/75072673/301311905-eadc50a0-799c-426d-9d41-6edcd9414385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDI5ODMsIm5iZiI6MTcwNjc0MjY4MywicGF0aCI6Ii83NTA3MjY3My8zMDEzMTE5MDUtZWFkYzUwYTAtNzk5Yy00MjZkLTlkNDEtNmVkY2Q5NDE0Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTk2N2FjYzFlYzQyZTlhNzhjZjUwZmFjMWFlZGNiZjNmNjU2ZDMwMTM2MTM0YThkNmY4MTVjYjdkZTk0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBmgOiZVVxmMqLvANhGWtcaqkZNCm9g5SZLTjYJKTIA)
> > 
> > 
> > `/ad/ svc`
> 
> ![image](https://private-user-images.githubusercontent.com/75072673/302032465-f9cfb161-87d9-40d9-a32d-42f886038f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjYyMzUsIm5iZiI6MTcwNjk2NTkzNSwicGF0aCI6Ii83NTA3MjY3My8zMDIwMzI0NjUtZjljZmIxNjEtODdkOS00MGQ5LWEzMmQtNDJmODg2MDM4ZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEzMTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3M2MzZTBiMWIzMjk1ZWQxODM2NmNmMGY5YWM4ZjJjZWYyOWFjODFhNWVhNmIwYmIwNDUzZjM2OGRlODUxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_C_bpwcFuZFtoK4fcG3ilur9c92x0DCccRRPhzVI_o)
> 
> Nothing shows...

1. This isn't the right place to talk about this
2. You gave the offset of the found svc call.

**Comment by CursedLand** [comment]
> > > > > It uses a svc call to detect if frida is running on the device. You'll have to intercept it to bypass the detection
> > > > 
> > > > 
> > > > Just checked `libpairipcore.so` SVC calls and it's none.
> > > > ![image](https://private-user-images.githubusercontent.com/75072673/301311905-eadc50a0-799c-426d-9d41-6edcd9414385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDI5ODMsIm5iZiI6MTcwNjc0MjY4MywicGF0aCI6Ii83NTA3MjY3My8zMDEzMTE5MDUtZWFkYzUwYTAtNzk5Yy00MjZkLTlkNDEtNmVkY2Q5NDE0Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTk2N2FjYzFlYzQyZTlhNzhjZjUwZmFjMWFlZGNiZjNmNjU2ZDMwMTM2MTM0YThkNmY4MTVjYjdkZTk0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBmgOiZVVxmMqLvANhGWtcaqkZNCm9g5SZLTjYJKTIA)
> > > 
> > > 
> > > `/ad/ svc`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/75072673/302032465-f9cfb161-87d9-40d9-a32d-42f886038f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjYyMzUsIm5iZiI6MTcwNjk2NTkzNSwicGF0aCI6Ii83NTA3MjY3My8zMDIwMzI0NjUtZjljZmIxNjEtODdkOS00MGQ5LWEzMmQtNDJmODg2MDM4ZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEzMTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3M2MzZTBiMWIzMjk1ZWQxODM2NmNmMGY5YWM4ZjJjZWYyOWFjODFhNWVhNmIwYmIwNDUzZjM2OGRlODUxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_C_bpwcFuZFtoK4fcG3ilur9c92x0DCccRRPhzVI_o)
> > Nothing shows...
> 
> 1. This isn't the right place to talk about this
> 2. You gave the offset of the found svc call right there in the command response

would it be possible to try contact you in discord?

**Comment by lico-n** [comment]
I will close this as this is no longer related to the tool.
