### ISSUE TITLE
Is it supported on APatch?

### ISSUE THREAD

**Issue by skycosth** [lico-n/ZygiskFrida#24]
Is it supported on APatch?

**Comment by lico-n** [comment]
No currently not supported

**Comment by skycosth** [comment]
Can you make it accommodating?

**Comment by lico-n** [comment]
Maybe when I have some more time I can try to research how it is working and see how it works. I have no device with apatch at hand currently.

**Comment by lico-n** [comment]
It's unsupported in the sense that I haven't tested against it. It could work out the box by chance, but there is currently no promise of compatibility.

**Comment by electrondefuser** [comment]
@skycosth I can confirm that this module works with APatch. I am attaching the screenshots for the same. U do need ZygiskNext module installed in the APModule (as @nitanmarcel pointed out).

![Screenshot_20240315_124634](https://github.com/lico-n/ZygiskFrida/assets/13671961/df2d9fe6-d77b-4d84-8f07-de46b9f2d014)
![Screenshot_20240315_124708](https://github.com/lico-n/ZygiskFrida/assets/13671961/6a62f09e-697d-4f5e-b676-5e08551fab66)
![Screenshot_20240315_124732](https://github.com/lico-n/ZygiskFrida/assets/13671961/867cb501-9bea-4d6b-b129-c18626a2ae70)

**Comment by lico-n** [comment]
Thanks for confirming
