### ISSUE TITLE
Can't connect to frida

### ISSUE THREAD

**Issue by lslinode** [lico-n/ZygiskFrida#25]
Hi, I have installed ZygiskFrida with Magisk and created the config files with target app but after i open the app. Im unable to launch frida `frida -U -n Gadget` returns `Failed to spawn: unable to connect to remote frida-server: closed`  i have recreated the config and also with simple config with `target_packages` but unable to run it. no Logcat result from `logcat -s ZygiskFridaa` either. Pls suggest. thanks

**Comment by lico-n** [comment]
Do you have zygisk enabled in magisk? Double checked the package name?

**Comment by lslinode** [comment]
Yes, it's enabled with denylist. tried different packages too.

**Comment by lico-n** [comment]
You can try a debug build downloaded from here: 
https://github.com/lico-n/ZygiskFrida/actions/runs/7679226044

It logs every app started, so at least you have some log output. 
Try to see if you see any output at all runinng `adb logcat -s ZygiskFrida` with this build. Otherwise also check in the magisk logs that zygisk started successfully.

**Comment by lslinode** [comment]
Thanks, installing it. will add feedback.

**Comment by lslinode** [comment]
Hi, seeing the logs and it works without `enforce denylist` on magisk. but without that the app doesn't work.

**Comment by lico-n** [comment]
Probably because normal magisk hides the root by also disabling zygisk for the application.

I myself am currently using magisk delta as their hiding method doesn't disable zygisk

**Comment by lslinode** [comment]
Can u share magisk delta's repo pls ?

**Comment by lico-n** [comment]
I think it's now named kitsune. Didn't update for a while but I think it is the successor?

https://github.com/HuskyDG/magisk-files

**Comment by lslinode** [comment]
Right, same with kitsune. the app is able to detect frida and shuts down.

**Comment by fantasticpanthom** [comment]
I am running into the same issue.

**Comment by lico-n** [comment]
I will close this for now. I can't really handle app specific anti detection individually. If you have any suggestions on how to further improve anti detection, I would appreciate any contributions.
