### ISSUE TITLE
Failed to Inject

### ISSUE THREAD

**Issue by ascorbic-acid** [lico-n/ZygiskFrida#26]
hello, thanks for this great tool. i want to inject custom lib but i could not due to perms error, I am using KernelSU with ZygiskNex. 

logcat:
```
E ZygiskFrida: Failed to inject /data/local/tmp/libfun.so (dlopen): dlopen failed: couldn't map "/data/local/tmp/libfun.so" segment 1: Permission denied
```

Note: **setenforce 0** did the trick but i guess that is not needed/good ?

**Comment by lico-n** [comment]
If the tool normally works for you, you can try to put the library into the `/data/local/tmp/re.zyg.fri` directory and just install the the same ZygiskFrida module over again. On install/reinstall it will setup the permission for all files in that directory.

The module sets the permission up with the predefined permission function from magisk. 

You can take a look at here https://github.com/topjohnwu/Magisk/blob/f86c66c99d165bee015c575057c02c7779170508/scripts/util_functions.sh#L568-L583

I call it like this https://github.com/lico-n/ZygiskFrida/blob/510e92700c4d0d55302bf8348ddebe92987e9ab7/template/magisk_module/customize.sh#L88

It's a combination of chown/chmod/chcon.

**Comment by ascorbic-acid** [comment]
thanks, that was the solution.

To save time i apply the module perms directly after adb push like:
```
chmod 644 libfun.so; chown root:root libfun.so; chcon u:object_r:system_file:s0 libfun.so
```
