### ISSUE TITLE
Advanced config doesn't seem to be working

### ISSUE THREAD

**Issue by andyacer** [lico-n/ZygiskFrida#27]
This tool is fantastic! Thanks for making it.

The instructions recommend using the Advanced configuration, but I can't get the tool to do anything that way.  It doesn't seem to respond to any app spawn events no matter what I do.  The simple configuration method does seem to be working though.  It behaves as expected where there's output on ADB and it intercepts the app spawn event.  It then waits for something to attach to the Frida gadget.

**Comment by lico-n** [comment]
Hey, 

could you provide the config that you are trying to use?

Is there no output at all when using the advanced config?

**Comment by andyacer** [comment]
Hey! Thanks for the fast reply.  Permissions was it.  I'll add chmod +r into a script I created to speed up changes.  We can close this.
<br>

<img width="692" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/25163515/819686d4-c5ca-41b8-8b35-e4b3553c275e">

**Comment by andyacer** [comment]
Permissions issue on the config file was the culprit here.
