### ISSUE TITLE
Advanced usage questions

### ISSUE THREAD

**Issue by TopMaps** [lico-n/ZygiskFrida#30]
Child gating mode: "inject", after configuring “/data/local/tmp/re.zyg.fri/libgadget-child.config.so”, need to add this “libgadget-child.config.so” to the path in injected_libraries?  Or how to configure it in other ways?

**Comment by lico-n** [comment]
You don't need to add the config to the injected libraries. It has to have the same name as the child gadget minus the config part.

So `libgadget-child.so` would be in the config and it would automatically use `libgadget-child.config.so`.
