### ISSUE TITLE
Loading module after building fails

### ISSUE THREAD

**Issue by DarKDevz** [lico-n/ZygiskFrida#41]
Windows 11
Device: arm64 zygisk

i followed the tutorial for building, after i push the zip file and try to load it in zygisk it says "installation failed" with no other info
if i load it from release version it works, but building it and using that doesnt ??

**Comment by lico-n** [comment]
Hmm that's weird. Maybe try building it with Android Studio. It's the IDE I was using for development. Though just using the command in Powershell is also working fine for me and builds it on Windows 11. 

The release version is always built by the CI which is built on linux but either version works for me.

Maybe try with Android Studio first and if it doesn't work maybe upload an example zip that doesn't work to take a look at.

**Comment by DarKDevz** [comment]
i am building from android studio, i also tried just running the command in powershell
but both didnt work, it might just be my machine's fault, i will try building from wsl later on

**Comment by misslng** [comment]
> i am building from android studio, i also tried just running the command in powershell but both didnt work, it might just be my machine's fault, i will try building from wsl later on

I have same question,do you solve it?
