### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by DoranekoSystems** [lico-n/ZygiskFrida#7]
Thanks for the great project. I think this tool can be used regardless of frida.
Can you add the ability to inject multiple arbitrary libraries other than frida-gadget?
(e.g. load all .so's under a certain directory)

**Comment by lico-n** [comment]
Hey,

I can see how being able to inject arbitrary .so files can be useful. 

I am thinking about adding an additional optional config file in the `re.zyg.fri` directory like `/data/local/tmp/re.zyg.fri/injected_libraries`.

In the absense of the file the frida-gadget would be loaded by default. 

If the file is present, then you can specify file paths to libs to be loaded. One library per line.
Libs are loaded in the order specified in the file.

F.e. 

```
/data/local/tmp/re.zyg.fri/libhelper.so
/data/local/tmp/some_other_path/libarbitrary.so
/data/local/tmp/re.zyg.fri/libgadget.so
```

Would first load libhelper, then libarbitrary and afterwards the gadget, making the libs available for usage with the gadget. 
It would also be possible to omit the gadget line for side use cases. 

This would keep the project focused on frida, expanding the feature set while also allowing for side use cases.

What do you think? Would this also fit your need?

**Comment by DoranekoSystems** [comment]
Thank you for your excellent suggestions.
It is exactly what I want.

**Comment by lico-n** [comment]
Thanks for the feature suggestion, I just created a new release v1.3.0 with this feature. If you encounter any issues, feel free to reach out again.
